on:
  push:
    branches:
      - main
      
permissions: write-all

jobs:
  my_first_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "images/diagram.svg"
          artifact_name: diagram
