on:
  push:
    branches:
      - main
      
permissions: write-all

jobs:
  my_first_job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Update diagram
        id: make_diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "output-diagram.svg"
          artifact_name: "my-diagram"
      - name: Get artifact
        uses: download-artifact@v4.3.0
        with:
          name: "diagram"
          path: "downloads"
