on:
  push:
    branches:
      - main

jobs:
  visualizer:
    name: visualises
    runs-on: ubuntu-latest
    steps:
      - name: Repo Visualizer
      - uses: githubocto/repo-visualizer@0.9.1
      - with:
          branch: "main"
          artifact_name: "diagram"

